server:
  port: 8080
spring:
  profiles:
    active: prod
  application:
    name: blog
  liquibase:
    change-log: classpath:/db/changelog/changelog.xml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
    banner-mode: off
