server:
  port: 8090
spring:
  application:
    name: blog
  profiles:
    active: dev
  liquibase:
    change-log: classpath:/db/changelog/changelog.xml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: false
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
    banner-mode: off