spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://47.98.148.158:5432/blog?ssl=true&sslmode=verify-ca&sslcert=D:\\certs\\client.crt&sslkey=D:\\certs\\client.pk8&sslrootcert=D:\\certs\\root.crt
    username: cuckooM
    password: cuckooM
logging:
  level:
    root: info
    com.cuckoom: debug