spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/blog
    username:
    password:
logging:
  level:
    root: info
    org.springframework: debug
    com.cuckoom: debug